# ====================================================================================

# FILE: k8s/network-policy.yaml

# DESCRIPTION: Network policies for microsegmentation

# SECURITY: Implements zero-trust networking

# ====================================================================================

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: default-deny-all
namespace: secure-notes
spec:
podSelector: {}
policyTypes:

- Ingress
- Egress

-----

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: postgres-policy
namespace: secure-notes
spec:
podSelector:
matchLabels:
app: postgres
policyTypes:

- Ingress
  ingress:
- from:
  - podSelector:
    matchLabels:
    app: backend-api
    ports:
  - protocol: TCP
    port: 5432

-----

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: backend-policy
namespace: secure-notes
spec:
podSelector:
matchLabels:
app: backend-api
policyTypes:

- Ingress
- Egress
  ingress:
- from:
  - podSelector:
    matchLabels:
    app: frontend
    ports:
  - protocol: TCP
    port: 5000
    egress:
- to:
  - podSelector:
    matchLabels:
    app: postgres
    ports:
  - protocol: TCP
    port: 5432
- to:
  - namespaceSelector: {}
    ports:
  - protocol: TCP
    port: 53
  - protocol: UDP
    port: 53

-----

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: frontend-policy
namespace: secure-notes
spec:
podSelector:
matchLabels:
app: frontend
policyTypes:

- Ingress
- Egress
  ingress:
- from: []
  ports:
  - protocol: TCP
    port: 8080
    egress:
- to:
  - podSelector:
    matchLabels:
    app: backend-api
    ports:
  - protocol: TCP
    port: 5000
- to:
  - namespaceSelector: {}
    ports:
  - protocol: TCP
    port: 53
  - protocol: UDP
    port: 53

-----
