# ====================================================================================

# FILE: k8s/postgres-service.yaml

# DESCRIPTION: Internal service for database access (ClusterIP)

# ====================================================================================

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: secure-notes
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
