# ====================================================================================

# FILE: k8s/rbac.yaml

# DESCRIPTION: Role-Based Access Control for the application

# ====================================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-notes-sa
  namespace: secure-notes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secure-notes-role
  namespace: secure-notes
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-notes-rolebinding
  namespace: secure-notes
subjects:
  - kind: ServiceAccount
    name: secure-notes-sa
    namespace: secure-notes
roleRef:
  kind: Role
  name: secure-notes-role
  apiGroup: rbac.authorization.k8s.io
